name: Call Skill Repo

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke action from Repo B
        uses: Himanshijain-2005/repob@main
        with:
          name: Radha Krishna 